import Head from 'next/head'
import Blog from './components/Blog/Blog'
import Customer from './components/Customer/Customer'
import Customers from './components/Customers/Customers'
import FeaturedSpace from './components/FeaturedSpace/FeaturedSpace'
import Footer from './components/Footer/Footer'
import Header from './components/Header/Header'
import { Navbar } from './components/Navbar/Navbar'
import Pricing from './components/Pricing/Pricing'
import Workspace from './components/Workspace/Workspace'
import './globals.css'

export const metadata = {
  title: 'Saas Modern Landing Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="shortcut icon" href="/images/favicon.ico" />
      </Head>
      <body className="2xl:px-[6rem] 2xl:py-6 lg:px-[1.875rem] lg:py-5 font-['DM-Sans']">
        <Navbar/>
        <div>
          <Header/>
          <Customer/>
          <FeaturedSpace/>
          <Workspace/>
          <Pricing/>
          <Customers/>
          <Blog/>
        </div>
        <Footer/>
      </body>
    </html>
  )
}
